<?php

namespace Agicom\Telemaque\Enums;

class Permission
{
    protected static $permission = [
        'collegeresident' => 'Collège - Président(e)',
        'college.president-cs' => 'Collège - Président(e) C.S.',
        'college.president-cndm' => 'Collège - Président(e) CNDM',
        'college.vicepresident' => 'Collège - Vice-Président(e)',
        'college.gerant' => 'Collège - Gérant(e)',
        'college.surveillant' => 'Collège - Surveillant(e)',
        'college.mediateur' => 'Collège - Médiateur(trice)',
        'college.member' => 'Collège - Membre',
        'orpifrance.president' => 'ORPI FRANCE - Président(e)',
        'orpifrance.member' => 'ORPI FRANCE - Membre',
        'orpifrance.responsable' => 'ORPI FRANCE - Responsable service',
        'agency.conseiller' => 'Agence - Conseiller(e)',
        'agency.conseiller.transaction' => 'Agence - Conseiller(e) en transaction',
        'agency.conseiller.location' => 'Agence - Conseiller(e) en location',
        'agency.conseiller.pro' => 'Agence - Conseiller(e) en immobilier professionel',
        'agency.conseiller.promo' => 'Agence - Conseiller(e) en promotion immobilière',
        'agency.conseiller.gestion' => 'Agence - Conseiller(e) en gestion de Patrimoine / Fiscal',
        'agency.conseiller.neuf' => 'Agence - Conseiller(e) en immobilier neuf',
        'agency.assistant' => 'Agence - Assistant(e)',
        'agency.assistant.transaction' => 'Agence - Assistant(e) en transaction',
        'agency.assistant.location' => 'Agence - Assistant(e) en location',
        'agency.assistant.pro' => 'Agence - Assistant(e) en immobilier professionel',
        'agency.assistant.promo' => 'Agence - Assistant(e) en promotion immobilière',
        'agency.assistant.gestion' => 'Agence - Assistant(e) en gestion de Patrimoine / Fiscal',
        'agency.assistant.neuf' => 'Agence - Assistant(e) en immobilier neuf',
        'agency.assistant.commercial' => 'Agence - Assistant(e) Commercial',
        'agency.copro' => 'Agence - Copropriété/Syndic',
        'agency.copro.gestion' => 'Agence - Copropriété/Syndic - Gestion Locative',
        'agency.copro.compta' => 'Agence - Copropriété/Syndic - Comptable',
        'agency.copro.dir' => 'Agence - Copropriété/Syndic - Direction',
        'agency.copro.rh' => 'Agence - Copropriété/Syndic - Ressources humaines',
        'agency.marketing' => 'Agence - Marketing',
        'agency.marketing.community' => 'Agence - Community Manager',
        'agency.marketing.com' => 'Agence - Chargé(e) de communication',
        'agency.marketing.graph' => 'Agence - Graphiste',
        'agency.compta' => 'Agence - Comptable',
        'agency.compta.societe' => 'Agence - Comptable en société',
        'agency.compta.syndic' => 'Agence - Comptable en Syndic de copropriété',
        'agency.compta.gestion' => 'Agence - Comptable en gestion locative',
        'agency.gestion' => 'Agence - Gestionnaire',
        'agency.gestion.location' => 'Agence - Gestionnaire Locatif',
        'agency.gestion.copro' => 'Agence - Gestionnaire de copropriétés',
        'agency.manager' => 'Agence - Manager',
        'agency.manager.transaction' => 'Agence - Manager en transaction',
        'agency.manager.location' => 'Agence - Manager en location',
        'agency.manager.pro' => 'Agence - Manager en immobilier professionel',
        'agency.manager.promo' => 'Agence - Manager en promotion immobilière',
        'agency.manager.neuf' => 'Agence - Manager en immobilier neuf',
        'agency.manager.gestion' => 'Agence - Manager en Gestion Locative',
        'agency.manager.syndic' => 'Agence - Manager Syndic',
        'agency.manager.commercial' => 'Agence - Manager Commercial',
        'agency.manager.rh' => 'Agence - Manager en Ressources Humaines',
        'agency.manager.compta' => 'Agence - Manager Comptable',
        'agency.responsable' => 'Agence - Responsable',
        'agency.responsable.transaction' => 'Agence - Responsable en transaction',
        'agency.responsable.location' => 'Agence - Responsable en location',
        'agency.responsable.pro' => 'Agence - Responsable en immobilier professionel',
        'agency.responsable.promo' => 'Agence - Responsable en promotion immobilière',
        'agency.responsable.neuf' => 'Agence - Responsable en immobilier neuf',
        'agency.responsable.gestion' => 'Agence - Responsable en Gestion Locative',
        'agency.responsable.syndic' => 'Agence - Responsable Syndic',
        'agency.responsable.commercial' => 'Agence - Responsable Commercial',
        'agency.responsable.rh' => 'Agence - Responsable en Ressources Humaines',
        'agency.responsable.compta' => 'Agence - Responsable Comptable',
        'agency.directeur' => 'Agence - Directeur(ice)',
        'agency.directeur.agence' => 'Agence - Directeur(ice) d\'agence',
        'agency.directeur.admin' => 'Agence - Directeur(ice) administratif et financier',
        'agency.directeur.rh' => 'Agence - Directeur(ice) des ressources humaines',
        'agency.directeur.syndic' => 'Agence - Directeur(ice) Syndic',
        'agency.directeur.gestion' => 'Agence - Directeur(ice) Gestion Locative',
        'agency.directeur.commercial' => 'Agence - Directeur(ice) Commercial',
        'agency.directeur.pro' => 'Agence - Directeur(ice) en Immobilier professionnel',
        'agency.directeur.promo' => 'Agence - Directeur(ice) en promotion Immobilière',
        'agency.directeur.dirigeant' => 'Agence - Dirigeant',
        'agency.directeur.gerant' => 'Agence - Gérant',
        'agency.directeur.president' => 'Agence - Président',
        'agency.directeur.general' => 'Agence - Directeur(ice) Général',
        'gie.president' => 'GIE - Président(e) du GIE',
        'gie.secretaire' => 'GIE - Secrétaire du GIE',
        'gie.tresorier' => 'GIE - Trésorier(e) du GIE',
        'gie.animation' => 'GIE - Responsable Animation et Controle interne',
        'gie.pub' => 'GIE - Responsable Publicité',
        'gie.formation' => 'GIE - Responsable Formation',
        'gie.recrutement' => 'GIE - Responsable Recrutement Associé et Collaborateur',
        'gie.discipline' => 'GIE - Responsable Discipline',
        'gie.assistant' => 'GIE - Assistant(e) du GIE',
        'gie.compta' => 'GIE - Controleur(euse) des Comptes',
        'gie.gestion' => 'GIE - Controleur(euse) de Gestion',
        'gie.dsi' => 'GIE - Responsable Informatique',
        'gie.adb' => 'GIE - Responsable ADB',
        'gie.vicepresident' => 'GIE - Vice président(e) du GIE',
        'gie.juridique' => 'GIE - Référent(e) juridique',
        'gie.partners' => 'GIE - Responsable Partenariats',
        'gie.cndm' => 'GIE - Président du Conseil Local de Discipline et Médiation',
        'gie.referent' => 'GIE - Consultant Référent GIE',
        'monagence.team' => 'MonAgence - Données équipe',
    ];

    public static function get(string $permission): string
    {
        // check if the permission exists and return it, else return 'none'
        return
        array_key_exists($permission, self::$permission) ?
        self::$permission[$permission] :
        'none';
    }
}
